apiVersion: apps/v1
kind: Deployment
metadata:
  name: isucondition
  labels:
    app: isucondition
    lang: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isucondition
      lang: golang
  template:
    metadata:
      labels:
        app: isucondition
        lang: golang
    spec:
      initContainers:
        - name: fetch-initdb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "wget -P /tmp https://github.com/isucon/isucon11-qualify/releases/download/public/1_InitData.sql"
          resources:
            limits:
              cpu: "100m"
              memory: 50Mi
          volumeMounts:
            - mountPath: /tmp
              name: init-volume
      containers:
        - name: isucondition
          image: ghcr.io/inductor/isucondition-golang:latest # FIXME: 実際に競技を再現したい場合はタグを変更しましょう
          imagePullPolicy: Always # FIXME: デバッグ用。タグ運用をするなら外しておいた方がよい。
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: isucondition-mysql
          resources:
            limits:
              cpu: "2000m"
              memory: 4Gi
          volumeMounts:
            - mountPath: /isucon/sql/1_InitData.sql
              readOnly: true
              subPath: 1_InitData.sql
              name: init-volume
      volumes:
      - name: init-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: isucondition
spec:
  type: ClusterIP
  ports:
    - name: isucondition
      port: 3000
  selector:
    app: isucondition
    lang: golang
