apiVersion: apps/v1
kind: Deployment
metadata:
  name: isucondition-golang
  labels:
    app: isucondition
    lang: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isucondition
      lang: golang
  template:
    metadata:
      labels:
        app: isucondition
        lang: golang
    spec:
      containers:
        - name: isucondition-golang
          image: nginx:1.22.0
          ports:
          - containerPort: 80
