apiVersion: apps/v1
kind: Deployment
metadata:
  name: isucondition-golang
  labels:
    app: isucondition
    lang: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isucondition
      lang: golang
  template:
    metadata:
      labels:
        app: isucondition
        lang: golang
    spec:
      containers:
        - name: isucondition-golang
          image: docker pull ghcr.io/inductor/isucon-golang:latest # FIXME: 実際に競技を再現したい場合はタグを変更しましょう
          ports:
          - containerPort: 80
