apiVersion: apps/v1
kind: Deployment
metadata:
  name: isucondition
  labels:
    app: isucondition
    lang: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isucondition
      lang: golang
  template:
    metadata:
      labels:
        app: isucondition
        lang: golang
    spec:
      containers:
        - name: isucondition
          image: docker pull ghcr.io/inductor/isucondition-golang:latest # FIXME: 実際に競技を再現したい場合はタグを変更しましょう
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: isucondition-mysql
          resources:
            limits:
              cpu: "4000m"
              memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: isucondition
spec:
  type: ClusterIP
  ports:
    - name: isucondition
      port: 3000
  selector:
    app: isucondition
    lang: golang
