apiVersion: batch/v1
kind: Job
metadata:
  name: isucondition-bench
  namespace: isucon-bench
  labels:
    app: bench
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: fetch-initdb
          image: busybox
          command:
            - "sh"
            - "-c"
            - "wget -P /tmp https://github.com/isucon/isucon11-qualify/releases/download/public/1_InitData.sql"
          resources:
            limits:
              cpu: "100m"
              memory: 50Mi
          volumeMounts:
            - mountPath: /tmp
              name: init-volume
        - name: fetch-json
          image: busybox
          command:
            - "sh"
            - "-c"
            - "wget -P /tmp https://github.com/isucon/isucon11-qualify/releases/download/public/initialize.json"
          resources:
            limits:
              cpu: "100m"
              memory: 50Mi
          volumeMounts:
            - mountPath: /tmp
              name: init-volume
        - name: fetch-images
          image: busybox
          command:
            - "sh"
            - "-c"
            - "wget -P /tmp https://github.com/isucon/isucon11-qualify/releases/download/public/images.tgz"
          resources:
          resources:
            limits:
              cpu: "100m"
              memory: 50Mi
          volumeMounts:
            - mountPath: /tmp
              name: init-volume
      containers:
        - name: bench
          image: ghcr.io/inductor/isucondition-bench:latest
          command:
            - "/isucon11-qualify/bench/bench"
            - "--exit-status"
          volumeMounts:
            - mountPath: /isucon11-qualify/bench/data
              name: init-volume
          env:
            - name: ISUXBENCH_TARGET
              value: "isucondition.isucon-app:3000"
            - name: ISUXBENCH_ALL_ADDRESSES
              value: "isucondition.isucon-app"
            - name: JIA_SERVICE_URL
              value: "http://isucondition-jiaapi-mock.mock:5000"
          resources:
            limits:
              cpu: "4000m"
              memory: 8Gi
      volumes:
      - name: init-volume
        emptyDir: {}
