apiVersion: apps/v1
kind: Deployment
metadata:
  name: isucondition-jiaapi-mock
  labels:
    app: jiaapi-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jiaapi-mock
  template:
    metadata:
      labels:
        app: jiaapi-mock
    spec:
      containers:
        - name: jiaapi-mock
          image: ghcr.io/inductor/isucondition-jiaapi-mock:latest
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jiaapi-mock
spec:
  type: ClusterIP
  ports:
    - name: jiaapi-mock
      port: 3000
  selector:
    app: jiaapi-mock
