---
- name: "common roles"
  hosts: all
  tags:
    - contestant
    - bench
    - standalone
  roles:
    - common
    - langs

- name: "contestant roles"
  hosts: [contestant]
  tags: [contestant]
  roles:
    - langs.go
    - langs.nodejs
    - langs.perl
    - langs.php
    - langs.python
    - langs.ruby
    - langs.rust
    - contestant

- name: "contestant roles for the qualify day"
  hosts: [contestant]
  tags: [qualify]
  roles:
    - contestant.envchecker

- name: "bench roles"
  hosts: [bench]
  tags: [bench]
  roles:
    - langs.go
    - langs.rust
    - bench

- name: "bench roles for the qualify day"
  hosts: [bench]
  tags: [qualify]
  roles:
    - bench.node_exporter
    - bench.supervisor

- name: "standalone roles"
  hosts: [standalone]
  roles:
    - langs.go
    - langs.nodejs
    - langs.perl
    - langs.php
    - langs.python
    - langs.ruby
    - langs.rust
    - contestant
    - bench

