name: CI
on: 
  push:
    paths:
      - '.github/workflows/bench.yaml'

env:
  BENCHK_IMAGE: ghcr.io/inductor/isucondition-bench
  JIAAPI_MOCK_IMAGE: ghcr.io/inductor/isucondition-jiaapi-mock
  go-version: 1.16.5

jobs:
  build-check:
    name: Lint and test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          cache-dependency-path: 'isucon11-qualify/webapp/go/go.sum'
          cache: true

      - name: Build ISUCON Go app
        run: go build
        working-directory: ./isucon11-qualify/webapp/go
  build-bench-image:
    name: Build docker image (and publish on master)
    needs: [build-check]
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.BENCHK_IMAGE }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=sha-,suffix=,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build (and push if on main)
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile.golang
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-mock-image:
    name: Build docker image (and publish on master)
    needs: [build-check]
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.JIAAPI_MOCK_IMAGE }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=sha-,suffix=,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build (and push if on main)
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile.golang
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max